view: sfd_power_ltv_ab {
  derived_table: {
    sql: SELECT
          install_date,
          platform,
          track_installs,
          -- country,
          experiment,
          AB_group,
          round(pred_D1_LTV,4) as pred_D1_LTV,
          round(pred_D1_LTV+ pred_D2_LTV,4) as pred_D2_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV,4) as pred_D3_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV,4) as pred_D4_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV,4) as pred_D5_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV,4) as pred_D6_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV,4) as pred_D7_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV,4) as pred_D8_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV,4) as pred_D9_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV,4) as pred_D10_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV,4) as pred_D11_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV,4) as pred_D12_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV,4) as pred_D13_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV,4) as pred_D14_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV,4) as pred_D15_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV,4) as pred_D16_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV+pred_D17_LTV,4) as pred_D17_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV+pred_D17_LTV+pred_D18_LTV,4) as pred_D18_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV+pred_D17_LTV+pred_D18_LTV+pred_D19_LTV,4) as pred_D19_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV+pred_D17_LTV+pred_D18_LTV+pred_D19_LTV+pred_D20_LTV,4) as pred_D20_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV+pred_D17_LTV+pred_D18_LTV+pred_D19_LTV+pred_D20_LTV+pred_D21_LTV,4) as pred_D21_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV+pred_D17_LTV+pred_D18_LTV+pred_D19_LTV+pred_D20_LTV+pred_D21_LTV+pred_D22_LTV,4) as pred_D22_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV+pred_D17_LTV+pred_D18_LTV+pred_D19_LTV+pred_D20_LTV+pred_D21_LTV+pred_D22_LTV+pred_D23_LTV,4) as pred_D23_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV+pred_D17_LTV+pred_D18_LTV+pred_D19_LTV+pred_D20_LTV+pred_D21_LTV+pred_D22_LTV+pred_D23_LTV+pred_D24_LTV,4) as pred_D24_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV+pred_D17_LTV+pred_D18_LTV+pred_D19_LTV+pred_D20_LTV+pred_D21_LTV+pred_D22_LTV+pred_D23_LTV+pred_D24_LTV+pred_D25_LTV,4) as pred_D25_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV+pred_D17_LTV+pred_D18_LTV+pred_D19_LTV+pred_D20_LTV+pred_D21_LTV+pred_D22_LTV+pred_D23_LTV+pred_D24_LTV+pred_D25_LTV+pred_D26_LTV,4) as pred_D26_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV+pred_D17_LTV+pred_D18_LTV+pred_D19_LTV+pred_D20_LTV+pred_D21_LTV+pred_D22_LTV+pred_D23_LTV+pred_D24_LTV+pred_D25_LTV+pred_D26_LTV+pred_D27_LTV,4) as pred_D27_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV+pred_D17_LTV+pred_D18_LTV+pred_D19_LTV+pred_D20_LTV+pred_D21_LTV+pred_D22_LTV+pred_D23_LTV+pred_D24_LTV+pred_D25_LTV+pred_D26_LTV+pred_D27_LTV+pred_D28_LTV,4) as pred_D28_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV+pred_D17_LTV+pred_D18_LTV+pred_D19_LTV+pred_D20_LTV+pred_D21_LTV+pred_D22_LTV+pred_D23_LTV+pred_D24_LTV+pred_D25_LTV+pred_D26_LTV+pred_D27_LTV+pred_D28_LTV+pred_D29_LTV,4) as pred_D29_LTV,
          round(pred_D1_LTV+ pred_D2_LTV+pred_D3_LTV+pred_D4_LTV+pred_D5_LTV+pred_D6_LTV+pred_D7_LTV+pred_D8_LTV+pred_D9_LTV+pred_D10_LTV+pred_D11_LTV+pred_D12_LTV+pred_D13_LTV+pred_D14_LTV+pred_D15_LTV+pred_D16_LTV+pred_D17_LTV+pred_D18_LTV+pred_D19_LTV+pred_D20_LTV+pred_D21_LTV+pred_D22_LTV+pred_D23_LTV+pred_D24_LTV+pred_D25_LTV+pred_D26_LTV+pred_D27_LTV+pred_D28_LTV+pred_D29_LTV+pred_D30_LTV,4) as pred_D30_LTV,

      FROM(
      SELECT
          install_date,
          ltvs.platform as platform,
          track_installs,
          experiment,
          AB_group,
          -- ltvs.country as country,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(1,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D1_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(2,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D2_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(3,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D3_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(4,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D4_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(5,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D5_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(6,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D6_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(7,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D7_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(8,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D8_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(9,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D9_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(10,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D10_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(11,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D11_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(12,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D12_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(13,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D13_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(14,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D14_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(15,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D15_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(16,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D16_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(17,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D17_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(18,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D18_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(19,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D19_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(20,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D20_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(21,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D21_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(22,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D22_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(23,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D23_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(24,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D24_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(25,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D25_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(26,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D26_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(27,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D27_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(28,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D28_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(29,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D29_LTV,
          exp((functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - ((ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5])*functions.sumLnx([1,2,3,4,5])))*functions.sumLnx([1,2,3,4,5])) / (ARRAY_LENGTH([1,2,3,4,5])))*power(30,(ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnxLny(False, install_date ,[1,2,3,4,5], [D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )]) - functions.sumLnx([1,2,3,4,5])*functions.sumLny(False, install_date ,[D0_revenue,D1_revenue,D2_revenue,D3_revenue,D4_revenue,avg(D3_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 8 preceding and 2 preceding ),avg(D4_revenue) OVER (partition by experiment, AB_group, ltvs.platform order by install_date rows between 9 preceding and 3 preceding )])) / (ARRAY_LENGTH([1,2,3,4,5]) * functions.sumLnx2([1,2,3,4,5]) - functions.sumLnx([1,2,3,4,5]) *functions.sumLnx([1,2,3,4,5]))) / track_installs as Pred_D30_LTV,

      FROM(
      SELECT
          (DATE(TIMESTAMP_MICROS(user_first_touch_timestamp))) as install_date,
          platform,
          experiment,
          AB_group,
          sum(track_installs) as track_installs,
          round(sum(D0_revenue),2) as D0_revenue,
          round(sum(D1_revenue),2) as D1_revenue,
          round(sum(D2_revenue),2) as D2_revenue,
          round(sum(D3_revenue),2) as D3_revenue,
          round(sum(D4_revenue),2) as D4_revenue
      from (
      SELECT DATE(PARSE_DATE('%Y%m%d',replace(suffix,"intraday_",""))) as date,
          user_first_touch_timestamp,
          user_pseudo_id,
          userProperty.key as experiment,
          userProperty.value.string_value as AB_group,
          platform,
          DATE_DIFF(DATE(PARSE_DATE('%Y%m%d',replace(suffix,"intraday_",""))), (DATE(TIMESTAMP_MICROS(user_first_touch_timestamp) )), DAY) as retention_day,
          (CASE WHEN (DATE_DIFF(DATE(PARSE_DATE('%Y%m%d',replace(suffix,"intraday_",""))), (DATE(TIMESTAMP_MICROS(user_first_touch_timestamp) )), DAY) =0 ) THEN COUNT(DISTINCT user_pseudo_id) ELSE NULL END) as track_installs,
          (CASE WHEN (DATE_DIFF(DATE(PARSE_DATE('%Y%m%d',replace(suffix,"intraday_",""))), (DATE(TIMESTAMP_MICROS(user_first_touch_timestamp) )), DAY) =0 )THEN COALESCE(SUM(((select value.double_value from UNNEST(events.event_params) where value.double_value IS NOT NULL AND event_name='ad_revenue'  ) ) ), 0)  ELSE 0.0 END) as D0_revenue,
          (CASE WHEN (DATE_DIFF(DATE(PARSE_DATE('%Y%m%d',replace(suffix,"intraday_",""))), (DATE(TIMESTAMP_MICROS(user_first_touch_timestamp) )), DAY) =1 )THEN COALESCE(SUM(((select value.double_value from UNNEST(events.event_params) where value.double_value IS NOT NULL AND event_name='ad_revenue'  ) ) ), 0)  ELSE 0.0 END) as D1_revenue,
          (CASE WHEN (DATE_DIFF(DATE(PARSE_DATE('%Y%m%d',replace(suffix,"intraday_",""))), (DATE(TIMESTAMP_MICROS(user_first_touch_timestamp) )), DAY) =2 )THEN COALESCE(SUM(((select value.double_value from UNNEST(events.event_params) where value.double_value IS NOT NULL AND event_name='ad_revenue'  ) ) ), 0)  ELSE 0.0 END) as D2_revenue,
          (CASE WHEN (DATE_DIFF(DATE(PARSE_DATE('%Y%m%d',replace(suffix,"intraday_",""))), (DATE(TIMESTAMP_MICROS(user_first_touch_timestamp) )), DAY) =3 )THEN COALESCE(SUM(((select value.double_value from UNNEST(events.event_params) where value.double_value IS NOT NULL AND event_name='ad_revenue'  ) ) ), 0)  ELSE 0.0 END) as D3_revenue,
          (CASE WHEN (DATE_DIFF(DATE(PARSE_DATE('%Y%m%d',replace(suffix,"intraday_",""))), (DATE(TIMESTAMP_MICROS(user_first_touch_timestamp) )), DAY) =4 )THEN COALESCE(SUM(((select value.double_value from UNNEST(events.event_params) where value.double_value IS NOT NULL AND event_name='ad_revenue'  ) ) ), 0)  ELSE 0.0 END) as D4_revenue,
      FROM `lk-datawarehouse-2.sfd_firebase.sfd_events` events,
          UNNEST(user_properties) as userProperty
          --End date + 2 days
          WHERE DATE(PARSE_DATE('%Y%m%d',replace(suffix,"intraday_",""))) >= DATE_SUB({% parameter end_day %}, INTERVAL 14 DAY)
          AND DATE(TIMESTAMP_MICROS(user_first_touch_timestamp)) BETWEEN DATE_SUB({% parameter end_day %}-2, INTERVAL 12 DAY) AND DATE_SUB({% parameter end_day %}, INTERVAL 2 DAY)
          and geo.country = "United States"
      group by 1, 2, 3, 4, 5, 6, suffix,user_first_touch_timestamp
      order by 2
          ) base
      group by 1,2,3,4
      order by 4,1
      )ltvs)
       ;;
  }

  measure: count {
    type: count
    drill_fields: [detail*]
  }

  parameter: end_day {
    type: date
  }

  dimension: install_date {
    type: date
    datatype: date
    sql: ${TABLE}.install_date ;;
  }

  dimension: platform {
    type: string
    sql: ${TABLE}.platform ;;
  }

  measure: track_installs {
    type: sum
    sql: ${TABLE}.track_installs ;;
  }

  dimension: experiment {
    type: string
    sql: ${TABLE}.experiment ;;
  }

  dimension: ab_group {
    type: string
    sql: ${TABLE}.AB_group ;;
  }

  measure: pred_d1_ltv {
    type: sum
    sql: ${TABLE}.pred_D1_LTV ;;
  }

  measure: pred_d2_ltv {
    type: sum
    sql: ${TABLE}.pred_D2_LTV ;;
  }

  measure: pred_d3_ltv {
    type: sum
    sql: ${TABLE}.pred_D3_LTV ;;
  }

  measure: pred_d4_ltv {
    type: sum
    sql: ${TABLE}.pred_D4_LTV ;;
  }

  measure: pred_d5_ltv {
    type: sum
    sql: ${TABLE}.pred_D5_LTV ;;
  }

  measure: pred_d6_ltv {
    type: sum
    sql: ${TABLE}.pred_D6_LTV ;;
  }

  measure: pred_d7_ltv {
    type: sum
    sql: ${TABLE}.pred_D7_LTV ;;
  }

  measure: pred_d8_ltv {
    type: sum
    sql: ${TABLE}.pred_D8_LTV ;;
  }

  measure: pred_d9_ltv {
    type: sum
    sql: ${TABLE}.pred_D9_LTV ;;
  }

  measure: pred_d10_ltv {
    type: sum
    sql: ${TABLE}.pred_D10_LTV ;;
  }

  measure: pred_d11_ltv {
    type: sum
    sql: ${TABLE}.pred_D11_LTV ;;
  }

  measure: pred_d12_ltv {
    type: sum
    sql: ${TABLE}.pred_D12_LTV ;;
  }

  measure: pred_d13_ltv {
    type: sum
    sql: ${TABLE}.pred_D13_LTV ;;
  }

  measure: pred_d14_ltv {
    type: sum
    sql: ${TABLE}.pred_D14_LTV ;;
  }

  measure: pred_d15_ltv {
    type: sum
    sql: ${TABLE}.pred_D15_LTV ;;
  }

  measure: pred_d16_ltv {
    type: sum
    sql: ${TABLE}.pred_D16_LTV ;;
  }

  measure: pred_d17_ltv {
    type: sum
    sql: ${TABLE}.pred_D17_LTV ;;
  }

  measure: pred_d18_ltv {
    type: sum
    sql: ${TABLE}.pred_D18_LTV ;;
  }

  measure: pred_d19_ltv {
    type: sum
    sql: ${TABLE}.pred_D19_LTV ;;
  }

  measure: pred_d20_ltv {
    type: sum
    sql: ${TABLE}.pred_D20_LTV ;;
  }

  measure: pred_d21_ltv {
    type: sum
    sql: ${TABLE}.pred_D21_LTV ;;
  }

  measure: pred_d22_ltv {
    type: sum
    sql: ${TABLE}.pred_D22_LTV ;;
  }

  measure: pred_d23_ltv {
    type: sum
    sql: ${TABLE}.pred_D23_LTV ;;
  }

  measure: pred_d24_ltv {
    type: sum
    sql: ${TABLE}.pred_D24_LTV ;;
  }

  measure: pred_d25_ltv {
    type: sum
    sql: ${TABLE}.pred_D25_LTV ;;
  }

  measure: pred_d26_ltv {
    type: sum
    sql: ${TABLE}.pred_D26_LTV ;;
  }

  measure: pred_d27_ltv {
    type: sum
    sql: ${TABLE}.pred_D27_LTV ;;
  }

  measure: pred_d28_ltv {
    type: sum
    sql: ${TABLE}.pred_D28_LTV ;;
  }

  measure: pred_d29_ltv {
    type: sum
    sql: ${TABLE}.pred_D29_LTV ;;
  }

  measure: pred_d30_ltv {
    type: sum
    sql: ${TABLE}.pred_D30_LTV ;;
  }

  set: detail {
    fields: [
      install_date,
      platform,
      track_installs,
      experiment,
      ab_group,
      pred_d1_ltv,
      pred_d2_ltv,
      pred_d3_ltv,
      pred_d4_ltv,
      pred_d5_ltv,
      pred_d6_ltv,
      pred_d7_ltv,
      pred_d8_ltv,
      pred_d9_ltv,
      pred_d10_ltv,
      pred_d11_ltv,
      pred_d12_ltv,
      pred_d13_ltv,
      pred_d14_ltv,
      pred_d15_ltv,
      pred_d16_ltv,
      pred_d17_ltv,
      pred_d18_ltv,
      pred_d19_ltv,
      pred_d20_ltv,
      pred_d21_ltv,
      pred_d22_ltv,
      pred_d23_ltv,
      pred_d24_ltv,
      pred_d25_ltv,
      pred_d26_ltv,
      pred_d27_ltv,
      pred_d28_ltv,
      pred_d29_ltv,
      pred_d30_ltv
    ]
  }
}
